# Generated by Django 4.0.1 on 2022-01-18 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_employment', models.CharField(choices=[('sal', 'Salaried'), ('self', 'Self-Salaried')], max_length=50)),
                ('designation', models.CharField(max_length=32)),
                ('year_of_exp', models.FloatField()),
                ('joining_date', models.DateField()),
                ('monthly_income', models.FloatField()),
                ('mode_of_salary', models.CharField(choices=[('ol', 'Online'), ('ch', 'Cheque'), ('c', 'Cash')], max_length=50)),
                ('company_address', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('itr', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=50)),
                ('avg_monthly_income', models.FloatField()),
                ('annual_turnover', models.FloatField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
            ],
        ),
    ]
