# Generated by Django 3.2.8 on 2022-01-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('customer_guarantor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cust_details', to='Customer.customer'),
        ),
    ]
