# Generated by Django 4.0.1 on 2022-01-18 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionedLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_loan', models.IntegerField(default=None)),
                ('approved_loan', models.IntegerField()),
                ('tenure', models.IntegerField()),
                ('interest', models.FloatField()),
                ('emi', models.FloatField(default=None)),
                ('is_approved', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
            ],
        ),
    ]
